services:
  - type: worker
    name: messenger-auto-reply
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python main.py
